#' National population reference file import function, with helper function
#'
#' This function gets the latest mid-year population estimates from ONS,
#' and imports it in a form to be used within MUMH Quarterly package.
#' There are arguments to specify year and geographical area.
#'
#' If error thrown by arguments, function shows users possible input values for year and area.
#'
#' @param url The url for the population data to be imported. Defaults to ONS source
#'
#' @param year The year/s to filter population by, should be a vector
#'
#' @param area The geographical area/s to filter population by, should be a vector
#'
#' @import dplyr, data.table
#'
#' @export
#'
#' @examples
#' ons_national_pop(year = 2020, area = ENPOP)
#' ons_national_pop(year = c(2015, 2017, 2019), area = c(GBPOP, ENPOP))
#' ons_national_pop(year = (2016:2020), area = UKPOP)
#'
#' @source \url{https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatestimeseriesdataset/current/}

ons_national_pop <- function(url = "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatestimeseriesdataset/current/pop.csv", year, area) {

  #trycatch checks if arguments valid, states possible valid inputs if not

  tryCatch(

    {
      df <- invisible(data.table::fread(url,
                                        skip = 7,
                                        col.names = c("YEAR","SCPOP","GBPOP",
                                                      "ENPOP","UKPOP","EWPOP",
                                                      "NIPOP","WAPOP")))

      #filter YEAR variable by any years in year input, select all area variables
      #from area input

      pop_df <- df %>%
        dplyr::filter(YEAR %in% year) %>%
        dplyr::select(YEAR, {{area}})


      #return error if year out of bounds gives empty data table

      if(nrow(pop_df) == 0) {stop ("Year not within range, data not returned")}

      return(pop_df)

      message("Function run with valid arguments")

    },

    #if arguments missing or invalid, generate error message

    error=function(error_message) {

      df_year <- invisible(data.table::fread(url,
                                             skip = 7, drop = 2:8, col.names = c("YEAR")))

      min_year <- df_year %>%
        dplyr::filter(YEAR == min(YEAR)) %>%
        pull(YEAR)

      max_year <- df_year %>%
        dplyr::filter(YEAR == max(YEAR)) %>%
        pull(YEAR)

      message(paste("Year or Area argument not valid"))
      message("Here is the warning generated by R:")
      message(error_message)


      message(paste(" The year argument must be a vector of any years between", min_year, "and", max_year))
      message('The area argument must be a vector of any areas from the following: "SCPOP","GBPOP","ENPOP","UKPOP",
              "EWPOP","NIPOP","WAPOP"')

      return(NA)

    }

  )

}
